# https://qodo-merge-docs.qodo.ai/installation/github/#run-as-a-github-action
on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: Fetch all labels
        id: labels
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "labels=${{ toJSON(github.event.pull_request.labels) }}" >> $GITHUB_OUTPUT
      - name: Check if label wants agent review
        if: |
          contains(join(fromJson(steps.labels.outputs.labels).*.[].name, ','), 'agent-review')
        run: echo "Tag 'agent-review' detected. Proceeding with workflow..."
      - name: PR Agent action step
        id: pragent
        if: |
          contains(join(fromJson(steps.labels.outputs.labels).*.[].name, ','), 'agent-review')
        uses: Codium-ai/pr-agent@sha256:96c1a4a6b0269e963afa90a2fb3ff5550e16e16d6d68f2fd727b2b995bb734d5
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
